import { Link } from "react-router-dom";
import { ArrowLeft, Zap } from "lucide-react";
import { useEffect } from "react";

const Disclaimer = () => {
  useEffect(() => {
    document.title = "Disclaimer | ShizenFlow";
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <nav className="fixed top-0 left-0 right-0 z-50 glass-card border-b border-border/30">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-4">
          <Link to="/" className="text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-5 w-5" />
          </Link>
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-lg bg-primary flex items-center justify-center">
              <Zap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="text-lg font-bold">Shizen<span className="gradient-text">Flow</span></span>
          </div>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 pt-28 pb-20">
        <h1 className="text-3xl md:text-4xl font-bold mb-2">Financial Disclaimer</h1>
        <p className="text-muted-foreground mb-10 text-sm">Last updated: February 28, 2026</p>

        <div className="space-y-8 text-foreground/90 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold mb-3">Not Financial Advice</h2>
            <p className="text-muted-foreground">ShizenFlow and its AI-generated content are provided for informational and educational purposes only. Nothing on this platform constitutes financial, investment, tax, legal, or accounting advice. You should not rely on any information provided by ShizenFlow as a substitute for professional financial guidance.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">AI Limitations</h2>
            <p className="text-muted-foreground">The AI-powered insights and recommendations generated by ShizenFlow are based on the data you provide and general financial principles. AI models can produce inaccurate, incomplete, or outdated information. ShizenFlow does not guarantee the accuracy, reliability, or completeness of any AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Investment Risks</h2>
            <p className="text-muted-foreground">All investments carry risk, including the potential loss of principal. Past performance does not guarantee future results. Any investment information or tracking provided by ShizenFlow should not be interpreted as an endorsement or recommendation of any specific investment strategy, security, or financial product.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">No Fiduciary Relationship</h2>
            <p className="text-muted-foreground">Use of ShizenFlow does not create a fiduciary relationship between you and ShizenFlow. We are not a registered investment advisor, broker-dealer, financial planner, or tax advisor. We do not hold, manage, or have custody of your actual financial assets.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Consult a Professional</h2>
            <p className="text-muted-foreground">Before making any financial decisions, you should consult with a qualified and licensed financial advisor, accountant, or tax professional who can provide advice tailored to your specific circumstances and risk tolerance.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Limitation of Liability</h2>
            <p className="text-muted-foreground">ShizenFlow shall not be held liable for any financial losses, damages, or adverse outcomes resulting from decisions made based on information provided through our platform. You acknowledge that you use ShizenFlow at your own risk.</p>
          </section>
        </div>
      </main>
    </div>
  );
};

export default Disclaimer;
